sudo: required

services:
  - docker

before_install:
- docker pull sabayon/base-armhfp

script:
- sudo sh -c "echo ':arm:M::\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x28\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-arm-binfmt:' > /proc/sys/fs/binfmt_misc/register"
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- ./build.sh armhfp sabayon/armhfp
- ./build.sh rpi sabayon/rpi-armhfp
- ./build.sh rpi-mc sabayon/rpi-mc-armhfp

notifications:
  irc: "chat.freenode.net#sabayon-infra"
